Twilight_Forest_MapScripts::
	.byte 0


Twilight_Forest_RagePowder::
# 4 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_RAGE_POWDER
# 5 "data/maps/Twilight_Forest/scripts.pory"
	msgbox Twilight_Forest_RagePowder_Text_0, MSGBOX_AUTOCLOSE
# 6 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_RAGEPOWDER
# 7 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 8
# 8 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_PollenPuff::
# 12 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_POLLEN_PUFF
# 13 "data/maps/Twilight_Forest/scripts.pory"
	msgbox Twilight_Forest_PollenPuff_Text_0, MSGBOX_AUTOCLOSE
# 14 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_POLLENPUFF
# 15 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 4
# 16 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_DarkPulse::
# 20 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_DARK_PULSE
# 21 "data/maps/Twilight_Forest/scripts.pory"
	msgbox Twilight_Forest_DarkPulse_Text_0, MSGBOX_AUTOCLOSE
# 22 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_DARKPULSE
# 23 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 3
# 24 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_ShadowClaw::
# 28 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_SHADOW_CLAW
# 29 "data/maps/Twilight_Forest/scripts.pory"
	msgbox Twilight_Forest_ShadowClaw_Text_0, MSGBOX_AUTOCLOSE
# 30 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_SHADOWCLAW
# 31 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 12
# 32 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_EnergyBall::
# 36 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_ENERGY_BALL
# 37 "data/maps/Twilight_Forest/scripts.pory"
	msgbox Twilight_Forest_EnergyBall_Text_0, MSGBOX_AUTOCLOSE
# 38 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_ENERGYBALL
# 39 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 9
# 40 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_AcidSpray::
# 44 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_ACID_SPRAY
# 45 "data/maps/Twilight_Forest/scripts.pory"
	msgbox Twilight_Forest_AcidSpray_Text_0, MSGBOX_AUTOCLOSE
# 46 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_ACIDSPRAY
# 47 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 1
# 48 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_PsychicTerrain::
# 52 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_PSYCHIC_TERRAIN
# 53 "data/maps/Twilight_Forest/scripts.pory"
	msgbox Twilight_Forest_PsychicTerrain_Text_0, MSGBOX_AUTOCLOSE
# 54 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_PSYCHICTERRAIN
# 55 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 14
# 56 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_PsychicFangs::
# 60 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_PSYCHIC_FANGS
# 61 "data/maps/Twilight_Forest/scripts.pory"
	msgbox Twilight_Forest_PsychicFangs_Text_0, MSGBOX_AUTOCLOSE
# 62 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_PSYCHICFANGS
# 63 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 11
# 64 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_BigRoot::
# 68 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_BIG_ROOT
# 69 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_BIGROOT
# 70 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 5
# 71 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_LightClay::
# 75 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_LIGHT_CLAY
# 76 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_LIGHTCLAY
# 77 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 2
# 78 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_PsychicSeed::
# 82 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_PSYCHIC_SEED
# 83 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_PSYCHICSEED
# 84 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 13
# 85 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_TwistedSpoon::
# 89 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TWISTED_SPOON
# 90 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_TWISTEDSPOON
# 91 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 10
# 92 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_SpellTag::
# 96 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_SPELL_TAG
# 97 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_SPELLTAG
# 98 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 6
# 99 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_DarkShards::
# 103 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_DARK_TERA_SHARD, 6
# 104 "data/maps/Twilight_Forest/scripts.pory"
	addvar VAR_DARK_SHARDS, 6
# 105 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_DARK_SHARDS_TWILIGHT
# 106 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 18
# 107 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_PsychicShards::
# 111 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_PSYCHIC_TERA_SHARD, 5
# 112 "data/maps/Twilight_Forest/scripts.pory"
	addvar VAR_PSYCHIC_SHARDS, 5
# 113 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_PSYCHIC_SHARDS_TWILIGHT
# 114 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 17
# 115 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_BugShards::
# 119 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_BUG_TERA_SHARD, 4
# 120 "data/maps/Twilight_Forest/scripts.pory"
	addvar VAR_BUG_SHARDS, 4
# 121 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_BUG_SHARDS_TWILIGHT
# 122 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 16
# 123 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_GrassShards::
# 127 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_GRASS_TERA_SHARD, 5
# 128 "data/maps/Twilight_Forest/scripts.pory"
	addvar VAR_GRASS_SHARDS, 5
# 129 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_GRASS_SHARDS_TWILIGHT
# 130 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 15
# 131 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_WaterShards::
# 135 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_WATER_TERA_SHARD, 8
# 136 "data/maps/Twilight_Forest/scripts.pory"
	addvar VAR_WATER_SHARDS, 8
# 137 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_WATER_SHARDS_TWILIGHT
# 138 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 7
# 139 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_RagePowder_Text_0:
# 5 "data/maps/Twilight_Forest/scripts.pory"
	.string "TM150 contains Rage Powder.$"

Twilight_Forest_PollenPuff_Text_0:
# 13 "data/maps/Twilight_Forest/scripts.pory"
	.string "TM86 contains Pollen Puff.$"

Twilight_Forest_DarkPulse_Text_0:
# 21 "data/maps/Twilight_Forest/scripts.pory"
	.string "TM72 contains Dark Pulse.$"

Twilight_Forest_ShadowClaw_Text_0:
# 29 "data/maps/Twilight_Forest/scripts.pory"
	.string "TM57 contains Shadow Claw.$"

Twilight_Forest_EnergyBall_Text_0:
# 37 "data/maps/Twilight_Forest/scripts.pory"
	.string "TM81 contains Energy Ball.$"

Twilight_Forest_AcidSpray_Text_0:
# 45 "data/maps/Twilight_Forest/scripts.pory"
	.string "TM123 contains Acid Spray.$"

Twilight_Forest_PsychicTerrain_Text_0:
# 53 "data/maps/Twilight_Forest/scripts.pory"
	.string "TM97 contains Psychic Terrain.$"

Twilight_Forest_PsychicFangs_Text_0:
# 61 "data/maps/Twilight_Forest/scripts.pory"
	.string "TM99 contains Psychic Fangs.$"
