Twilight_Forest_MapScripts::
	.byte 0


Twilight_Forest_RagePowder::
# 4 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_RAGE_POWDER
# 5 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_RAGEPOWDER
# 6 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 8
# 7 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_PollenPuff::
# 11 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_POLLEN_PUFF
# 12 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_POLLENPUFF
# 13 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 4
# 14 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_DarkPulse::
# 18 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_DARK_PULSE
# 19 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_DARKPULSE
# 20 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 3
# 21 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_ShadowClaw::
# 25 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_SHADOW_CLAW
# 26 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_SHADOWCLAW
# 27 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 12
# 28 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_SolarBlade::
# 32 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_SOLAR_BLADE
# 33 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_SOLARBLADE
# 34 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 7
# 35 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_EnergyBall::
# 39 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_ENERGY_BALL
# 40 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_ENERGYBALL
# 41 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 9
# 42 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_AcidSpray::
# 46 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_ACID_SPRAY
# 47 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_ACIDSPRAY
# 48 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 1
# 49 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_PsychicTerrain::
# 53 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_PSYCHIC_TERRAIN
# 54 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_PSYCHICTERRAIN
# 55 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 1
# 56 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_PsychicFangs::
# 60 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TM_PSYCHIC_FANGS
# 61 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_PSYCHICFANGS
# 62 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 11
# 63 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_BigRoot::
# 67 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_BIG_ROOT
# 68 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_BIGROOT
# 69 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 5
# 70 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_LightClay::
# 74 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_LIGHT_CLAY
# 75 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_LIGHTCLAY
# 76 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 2
# 77 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_PsychicSeed::
# 81 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_PSYCHIC_SEED
# 82 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_PSYCHICSEED
# 83 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 13
# 84 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_TwistedSpoon::
# 88 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_TWISTED_SPOON
# 89 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_TWISTEDSPOON
# 90 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 10
# 91 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_SpellTag::
# 95 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_SPELL_TAG
# 96 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_SPELLTAG
# 97 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 6
# 98 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_DarkShards::
# 102 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_DARK_TERA_SHARD, 5
# 103 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_DARK_SHARDS_TWILIGHT
# 104 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 18
# 105 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_PsychicShards::
# 109 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_PSYCHIC_TERA_SHARD, 5
# 110 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_PSYCHIC_SHARDS_TWILIGHT
# 111 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 17
# 112 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_BugShards::
# 116 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_BUG_TERA_SHARD, 5
# 117 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_BUG_SHARDS_TWILIGHT
# 118 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 16
# 119 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end


Twilight_Forest_GrassShards::
# 123 "data/maps/Twilight_Forest/scripts.pory"
	giveitem ITEM_GRASS_TERA_SHARD, 5
# 124 "data/maps/Twilight_Forest/scripts.pory"
	addvar VAR_GRASS_SHARDS, 5
# 125 "data/maps/Twilight_Forest/scripts.pory"
	setflag FLAG_GRASS_SHARDS_TWILIGHT
# 126 "data/maps/Twilight_Forest/scripts.pory"
	removeobject 15
# 127 "data/maps/Twilight_Forest/scripts.pory"
	closemessage
	end

