Prometheus_Tech_HQ_MapScripts::
	.byte 0


Prometheus_Tech_HQ_WarpPV::
# 5 "data/maps/Prometheus_Tech_HQ/scripts.pory"
	lockall
# 6 "data/maps/Prometheus_Tech_HQ/scripts.pory"
	faceplayer
# 7 "data/maps/Prometheus_Tech_HQ/scripts.pory"
	msgbox Prometheus_Tech_HQ_WarpPV_Text_0, MSGBOX_AUTOCLOSE
# 8 "data/maps/Prometheus_Tech_HQ/scripts.pory"
	releaseall
	end


Prometheus_Tech_HQ_WarpPV_Text_0:
# 7 "data/maps/Prometheus_Tech_HQ/scripts.pory"
	.string "This is the warp to Port Valor$"
